ARG NODE_IMAGE=node:16.19.0-alpine
ARG APP_PORT=3000

# =====================================
FROM ${NODE_IMAGE}

WORKDIR /home/app

RUN apk update && apk upgrade && apk add --no-cache bash git

EXPOSE $APP_PORT
