name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create environment file
        run: |
          cp example.env .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASS=${{ secrets.DB_PASS }} >> .env
          echo MAIL_USER=${{ secrets.MAIL_USER }} >> .env
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> .env
          echo PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} >> .env
          echo PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }} >> .env
          echo PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }} >> .env
          echo CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }} >> .env
          echo CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }} >> .env
          echo CLIENT_CERT_URL=${{ secrets.FIREBASE_CLIENT_CERT_URL }} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_PASS=${{ secrets.REDIS_PASS }} >> .env
          echo WORKER_EVENT=${{ secrets.WORKER_EVENT }} >> .env
          echo WORKER_CRON=${{ secrets.WORKER_CRON }} >> .env
          echo WORKER_MAIL=${{ secrets.WORKER_MAIL }} >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker Image Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: ./
          file: ./docker/Dockerfile.prod
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/safe-talk-worker-dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify image
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Install cloudflare cli and install sshpass
        run: |
          chmod +x ./scripts/install-cloudflared.sh
          ./scripts/install-cloudflared.sh
          mkdir ~/.ssh
          echo "${{ secrets.SSH_SCRIPT }}" >> ~/.ssh/config
          sudo apt install sshpass

      - name: SSH to server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no hana-server './ci-cd/safe-talk-worker-dev.sh'
